p8105_hw2_yz4994
================
2025-09-29

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(dplyr)
library(readr)
library(lubridate)
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

# Problem 1

## Dataset pols_month

``` r
#clean and manipulate the pols_month data
pols_df <- read_csv("./fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month=recode(month, `01` ="January", `02`= "February", `03`= "March", `04`= "April", `05`= "May",`06`= "June",`07`= "July",`08`= "August",`09`= "September",`10`= "October",`11`= "November",`12`= "December"), 
    month = factor(month, levels = month.name, ordered = TRUE),
    president = if_else(prez_gop == 1, "gop","dem")
  ) |>
  select(-prez_gop, -prez_dem, -day) |>
  arrange(year, month)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_df
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <ord>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

## Dataset snp

``` r
snp_df<- read_csv("./fivethirtyeight_datasets/snp.csv", na = c("NA", ".", "")) |>
  janitor::clean_names()|>
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) |>
  mutate(
    month=recode(month, `1` ="January", `2`= "February", `3`= "March", `4`= "April", `5`= "May",`6`= "June",`7`= "July",`8`= "August",`9`= "September",`10`= "October",`11`= "November",`12`= "December"),
    month = factor(month, levels = month.name, ordered = TRUE),
    year = if_else(year > 25, 1900 + as.numeric(year), 2000 + as.numeric(year)))|>
  select(year, month, close)|>
  arrange(year, month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df
```

    ## # A tibble: 787 × 3
    ##     year month     close
    ##    <dbl> <ord>     <dbl>
    ##  1  1950 January    17.0
    ##  2  1950 February   17.2
    ##  3  1950 March      17.3
    ##  4  1950 April      18.0
    ##  5  1950 May        18.8
    ##  6  1950 June       17.7
    ##  7  1950 July       17.8
    ##  8  1950 August     18.4
    ##  9  1950 September  19.5
    ## 10  1950 October    19.5
    ## # ℹ 777 more rows

## Dataset unemployment

``` r
unemployment_df <- read_csv("./fivethirtyeight_datasets/unemployment.csv") |>
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(
    month = recode(month,
      "Jan" = "January", "Feb" = "February", "Mar" = "March",
      "Apr" = "April", "May" = "May", "Jun" = "June",
      "Jul" = "July", "Aug" = "August", "Sep" = "September",
      "Oct" = "October", "Nov" = "November", "Dec" = "December"),
    month = factor(month, levels = month.name, ordered = TRUE)) |>
  rename(year = Year) |>
  arrange(year, month)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_df
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <dbl> <ord>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ℹ 806 more rows

## Merge the three datasets

``` r
merged <-
  inner_join(pols_df,snp_df, by = c("year", "month")) |>
  inner_join(unemployment_df, by = c("year", "month"))|>
  mutate(month = factor(month, levels = month.name, ordered = TRUE))|>
  arrange(year,month)

merged
```

    ## # A tibble: 786 × 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <ord>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1950 January      18      44     177      29      57     269 dem        17.0
    ##  2  1950 Februa…      18      44     177      29      57     269 dem        17.2
    ##  3  1950 March        18      44     177      29      57     269 dem        17.3
    ##  4  1950 April        18      44     177      29      57     269 dem        18.0
    ##  5  1950 May          18      44     177      29      57     269 dem        18.8
    ##  6  1950 June         18      44     177      29      57     269 dem        17.7
    ##  7  1950 July         18      44     177      29      57     269 dem        17.8
    ##  8  1950 August       18      44     177      29      57     269 dem        18.4
    ##  9  1950 Septem…      18      44     177      29      57     269 dem        19.5
    ## 10  1950 October      18      44     177      29      57     269 dem        19.5
    ## # ℹ 776 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

## About these datasets

The pols-month dataset contained information on the number of national
politicians by party affiliation, along with which party held the
presidency for each month between 1947 and 2015. The snp dataset
included closing values of the S&P stock index, also organized by month
and year. The unemployment dataset reported monthly unemployment
percentages for the U.S. population, originally in wide format but
reshaped into long format for merging. After cleaning and merging, the
resulting dataset contains 822 rows and variables such as year, month,
number of politicians (by party), president (gop/dem), S&P closing
values, and unemployment rates. The data cover the period from 1950
through 2015, and can now be used for analyses of relationships between
politics, markets, and unemployment trends.

# Problem 2

## Mr. Trash Wheel data

``` r
library(tidyverse)
library(readxl)

mr_trash <- read_excel("./trash/202509 Trash Wheel Collection Data.xlsx",
                       sheet = "Mr. Trash Wheel",
                       range = "A2:M709") |>   # skip notes, only data rows/cols
  janitor::clean_names() |>
  drop_na(dumpster) |>                       # delete rows with missind data
  mutate(sports_balls = as.integer(round(sports_balls, 0)),year=as.integer(year))

mr_trash
```

    ## # A tibble: 707 × 13
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 697 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>

## Professor Trash Wheel

``` r
prof_trash <- read_excel("./trash/202509 Trash Wheel Collection Data.xlsx",
                         sheet = "Professor Trash Wheel",
                         range = "A2:M134") |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(year=as.integer(year))

prof_trash
```

    ## # A tibble: 132 × 13
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 122 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

## gwynnda

``` r
gwynnda <- read_excel("./trash/202509 Trash Wheel Collection Data.xlsx",
                      sheet = "Gwynns Falls Trash Wheel",
                      range = "A2:L351") |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(year=as.integer(year))
gwynnda
```

    ## # A tibble: 349 × 12
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 339 more rows
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

## combine datasets

``` r
mr_trash<-mr_trash|>mutate(wheel="Mr Trash Wheel")
prof_trash<-prof_trash|>mutate(wheel="Professor Trash Wheel")
gwynnda<-gwynnda|>mutate(wheel="Gwynnda")
trash_wheels<-bind_rows(mr_trash,prof_trash,gwynnda)

library(dplyr)

trash_wheels
```

    ## # A tibble: 1,188 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,178 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, wheel <chr>, homes_powered <dbl>

The comnined trash wheel data has **1188** observations. The dataset
`mr.trash_df` include **707** dumpsters. The dataset
`professor_trash_df` include **132** dumpsters. The dataset
`gwynnda_trash_df` include **349** dumpsters.

The combined dataset has the following variables: **dumpster, month,
year, date, weight_tons, volume_cubic_yards, plastic_bottles,
polystyrene, cigarette_butts, glass_bottles, plastic_bags, wrappers,
sports_balls, wheel, homes_powered**

The examples of the key variables are as listed above. Across all
available observations, the total weight of trash collected by Professor
Trash Wheel was **282.26** tons. In June 2022, Gwynnda collected a total
of **1.812^{4}** cigarette butts.

# Problem 3

``` r
# import dataset
zip_codes <- read_csv("./zillow_data/Zip Codes.csv")
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zori <- read_csv("./zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv")
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# clean dataset
zip_codes_clean <- zip_codes |>
  select(
    zip = ZipCode,
    county = County,
    neighborhood = Neighborhood
  ) |>
  distinct()
```

``` r
# lean Zillow ZORI dataset
zori_clean <- zori |>
  rename(zip = RegionName) |>
  pivot_longer(
    cols = !RegionID:CountyName,  # all the date columns
    names_to = "date",
    values_to = "zori"
  ) |>
  mutate(
    date = ymd(date),
    zip = as.integer(zip)
  ) |>
  select(zip, CountyName, date, zori)


# merge datasets
zori_merged <- zori_clean |>
  left_join(zip_codes_clean, by = "zip",relationship = "many-to-many")|>
  select(date, zip,CountyName, neighborhood, zori,-county)
```

``` r
# number of total observations
n_obs <- nrow(zori_merged)

# number of unique ZIP codes and neighborhoods
n_zip <- n_distinct(zori_merged$zip)
n_neigh <- n_distinct(na.omit(zori_merged$neighborhood))

# ZIP codes in zip_codes but not in ZORI
zip_missing <- setdiff(zip_codes_clean$zip, zori_clean$zip)
```

``` r
# COVID rental drop (Jan 2020 vs Jan 2021)
covid_drop <- zori_merged |>
  filter(date %in% c("2020-01-31", "2021-01-31")) |>
  pivot_wider(names_from = date, values_from = zori,values_fn=mean) |>
  mutate(drop = `2021-01-31` - `2020-01-31`) |>
  arrange(drop) |>
  slice_head(n = 10) |>
  select(zip, CountyName, neighborhood, `2020-01-31`, `2021-01-31`, drop)
  covid_drop
```

    ## # A tibble: 10 × 6
    ##      zip CountyName      neighborhood            `2020-01-31` `2021-01-31`  drop
    ##    <dbl> <chr>           <chr>                          <dbl>        <dbl> <dbl>
    ##  1 10007 New York County Lower Manhattan                6334.        5422. -913.
    ##  2 10069 New York County <NA>                           4623.        3875. -748.
    ##  3 10009 New York County Lower East Side                3406.        2692. -714.
    ##  4 10016 New York County Gramercy Park and Murr…        3731.        3019. -712.
    ##  5 10001 New York County Chelsea and Clinton            4108.        3398. -710.
    ##  6 10002 New York County Lower East Side                3645.        2935. -710.
    ##  7 10004 New York County Lower Manhattan                3150.        2444. -706.
    ##  8 10038 New York County Lower Manhattan                3573.        2876. -698.
    ##  9 10012 New York County Greenwich Village and …        3629.        2942. -686.
    ## 10 10010 New York County Gramercy Park and Murr…        3697.        3012. -685.

After cleaning and merging, the resulting tidy dataset contains
**17516** total observations.  
It includes **149** unique ZIP codes and **42** unique neighborhoods
across the five boroughs of New York City.

**149** unique ZIP codes exist in the ZIP code dataset but not in the
Zillow dataset — for example,  
**10464, 10474, 10475, 10499, 10550**.  
These ZIP codes are often excluded because they may correspond to
**non-residential areas** (e.g., large commercial or industrial
zones),  
**P.O. boxes**, or ZIPs with **insufficient rental market data** for
Zillow to estimate a rent index.

Rental prices fluctuated dramatically during the COVID-19 pandemic.

Comparing January 2021 to January 2020 across all ZIP codes, the table
below shows the ten ZIP codes with the largest decline in rent prices:

### Comments on the TOP 10 rental prices drop ZIP code

``` r
covid_drop
```

    ## # A tibble: 10 × 6
    ##      zip CountyName      neighborhood            `2020-01-31` `2021-01-31`  drop
    ##    <dbl> <chr>           <chr>                          <dbl>        <dbl> <dbl>
    ##  1 10007 New York County Lower Manhattan                6334.        5422. -913.
    ##  2 10069 New York County <NA>                           4623.        3875. -748.
    ##  3 10009 New York County Lower East Side                3406.        2692. -714.
    ##  4 10016 New York County Gramercy Park and Murr…        3731.        3019. -712.
    ##  5 10001 New York County Chelsea and Clinton            4108.        3398. -710.
    ##  6 10002 New York County Lower East Side                3645.        2935. -710.
    ##  7 10004 New York County Lower Manhattan                3150.        2444. -706.
    ##  8 10038 New York County Lower Manhattan                3573.        2876. -698.
    ##  9 10012 New York County Greenwich Village and …        3629.        2942. -686.
    ## 10 10010 New York County Gramercy Park and Murr…        3697.        3012. -685.

The largest decline was in ZIP 10007 (Lower Manhattan), with a drop of
about \$913, from \$6334 to \$5422. Other steep declines (–\$700 to
–\$750) occurred in 10069 (Upper West Side / Riverside area), 10009
(Lower East Side), and 10016 (Gramercy / Murray Hill). The smallest of
the “top 10” was 10010 (Gramercy / Murray Hill) with a drop of about
\$684. All 10 ZIP codes are in Manhattan, indicating that this borough
was most heavily affected. Neighborhoods like Lower Manhattan, Lower
East Side, Gramercy, Chelsea, Greenwich Village, and SoHo dominate the
list. These areas are usually dense, expensive rental markets with heavy
reliance on office workers, students, and international residents.

During the COVID-19 pandemic (2020–2021), remote work and out-migration
reduced demand for Manhattan rentals, leading to dramatic price
declines. Outer-borough neighborhoods (e.g., Queens, Bronx, Staten
Island) are absent from the top 10, suggesting less dramatic
fluctuations there.

ZIP 10069 has missing neighborhood info, but is known to cover part of
the Upper West Side / Riverside South, an upscale area also impacted by
decreased demand.
