---
title: "p8105_hw2_yz4994"
output: github_document
date: "2025-09-29"
---
```{R load library}
library(tidyverse)
library(dplyr)
library(readr)
library(lubridate)
library(janitor)
```
# Problem 1
## Dataset pols_month
```{R import and clean pols dataset}
#clean and manipulate the pols_month data
pols_df <- read_csv("./fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month=recode(month, `01` ="January", `02`= "February", `03`= "March", `04`= "April", `05`= "May",`06`= "June",`07`= "July",`08`= "August",`09`= "September",`10`= "October",`11`= "November",`12`= "December"), 
    month = factor(month, levels = month.name, ordered = TRUE),
    president = if_else(prez_gop == 1, "gop","dem")
  ) |>
  select(-prez_gop, -prez_dem, -day) |>
  arrange(year, month)

pols_df
```
## Dataset snp
```{R import and clean dataset snp}
snp_df<- read_csv("./fivethirtyeight_datasets/snp.csv", na = c("NA", ".", "")) |>
  janitor::clean_names()|>
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) |>
  mutate(
    month=recode(month, `1` ="January", `2`= "February", `3`= "March", `4`= "April", `5`= "May",`6`= "June",`7`= "July",`8`= "August",`9`= "September",`10`= "October",`11`= "November",`12`= "December"),
    month = factor(month, levels = month.name, ordered = TRUE),
    year = if_else(year > 25, 1900 + as.numeric(year), 2000 + as.numeric(year)))|>
  select(year, month, close)|>
  arrange(year, month)

snp_df
```
## Dataset unemployment
```{R}
unemployment_df <- read_csv("./fivethirtyeight_datasets/unemployment.csv") |>
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(
    month = recode(month,
      "Jan" = "January", "Feb" = "February", "Mar" = "March",
      "Apr" = "April", "May" = "May", "Jun" = "June",
      "Jul" = "July", "Aug" = "August", "Sep" = "September",
      "Oct" = "October", "Nov" = "November", "Dec" = "December"),
    month = factor(month, levels = month.name, ordered = TRUE)) |>
  rename(year = Year) |>
  arrange(year, month)

unemployment_df
```
## Merge the three datasets
```{R}
merged <-
  inner_join(pols_df,snp_df, by = c("year", "month")) |>
  inner_join(unemployment_df, by = c("year", "month"))|>
  mutate(month = factor(month, levels = month.name, ordered = TRUE))|>
  arrange(year,month)

merged
```
## About these datasets
The pols-month dataset contained information on the number of national politicians by party affiliation, along with which party held the presidency for each month between 1947 and 2015. The snp dataset included closing values of the S&P stock index, also organized by month and year. The unemployment dataset reported monthly unemployment percentages for the U.S. population, originally in wide format but reshaped into long format for merging. After cleaning and merging, the resulting dataset contains 822 rows and variables such as year, month, number of politicians (by party), president (gop/dem), S&P closing values, and unemployment rates. The data cover the period from 1950 through 2015, and can now be used for analyses of relationships between politics, markets, and unemployment trends.

# Problem 2
## Mr. Trash Wheel data
```{R Mr.Trash Wheel data}
library(tidyverse)
library(readxl)

mr_trash <- read_excel("./trash/202509 Trash Wheel Collection Data.xlsx",
                       sheet = "Mr. Trash Wheel",
                       range = "A2:M709") |>   # skip notes, only data rows/cols
  janitor::clean_names() |>
  drop_na() |>                       # delete rows with missind data
  mutate(sports_balls = as.integer(round(sports_balls, 0)),year=as.integer(year))

mr_trash
```
## Professor Trash Wheel
```{R professor trash wheel}
prof_trash <- read_excel("./trash/202509 Trash Wheel Collection Data.xlsx",
                         sheet = "Professor Trash Wheel",
                         range = "A2:M134") |>
  janitor::clean_names() |>
  drop_na() |>
  mutate(year=as.integer(year))

prof_trash
```
## gwynnda
```{R gwynnda}
gwynnda <- read_excel("./trash/202509 Trash Wheel Collection Data.xlsx",
                      sheet = "Gwynns Falls Trash Wheel",
                      range = "A2:L351") |>
  janitor::clean_names() |>
  drop_na() |>
  mutate(year=as.integer(year))
gwynnda
```
## combine datasets
```{R comnine dataset}
mr_trash<-mr_trash|>mutate(wheel="Mr Trash Wheel")
prof_trash<-prof_trash|>mutate(wheel="Professor Trash Wheel")
gwynnda<-gwynnda|>mutate(wheel="Gwynnda")
trash_wheels<-bind_rows(mr_trash,prof_trash,gwynnda)

library(dplyr)

trash_wheels
```
The comnined trash wheel data has **`r nrow(trash_wheels)`** observations.
The dataset `mr.trash_df` include **`r nrow(mr_trash) `** dumpsters. The dataset `professor_trash_df` include **`r nrow(prof_trash) `** dumpsters. The dataset `gwynnda_trash_df` include **`r nrow(gwynnda) `** dumpsters.

The combined dataset has the following variables: **`r paste(names(trash_wheels), collapse = ", ")`**

The examples of the key variables are as listed above.
Across all available observations, the total weight of trash collected by Professor Trash Wheel was **`r sum(prof_trash$weight_tons,na.rm=TRUE)`** tons. 
In June 2022, Gwynnda collected a total of **`r sum(filter(trash_wheels, month=="June", year==2022,wheel=="Gwynnda")$cigarette_butts, na.rm = TRUE)`** cigarette butts.
However, we could find that the 0 cigarette butts is from the new and processed dataset which drops the rows with missing data. The original dataset shows that 18120 cigarette butts in June 2022.

# Problem 3
```{R import and clean dataset}
# import dataset
zip_codes <- read_csv("./zillow_data/Zip Codes.csv")
zori <- read_csv("./zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv")

# clean dataset
zip_codes_clean <- zip_codes |>
  select(
    zip = ZipCode,
    county = County,
    neighborhood = Neighborhood
  ) |>
  distinct()
```

```{R pivot table}
# lean Zillow ZORI dataset
zori_clean <- zori |>
  rename(zip = RegionName) |>
  pivot_longer(
    cols = !RegionID:CountyName,  # all the date columns
    names_to = "date",
    values_to = "zori"
  ) |>
  mutate(
    date = ymd(date),
    zip = as.integer(zip)
  ) |>
  select(zip, CountyName, date, zori)


# merge datasets
zori_merged <- zori_clean |>
  left_join(zip_codes_clean, by = "zip",relationship = "many-to-many")|>
  select(date, zip,CountyName, neighborhood, zori,-county)

```

```{R Calculate number we need}
# number of total observations
n_obs <- nrow(zori_merged)

# number of unique ZIP codes and neighborhoods
n_zip <- n_distinct(zori_merged$zip)
n_neigh <- n_distinct(na.omit(zori_merged$neighborhood))

# ZIP codes in zip_codes but not in ZORI
zip_missing <- setdiff(zip_codes_clean$zip, zori_clean$zip)


# COVID rental drop (Jan 2020 vs Jan 2021)
covid_drop <- zori_merged |>
  filter(date %in% c("2020-01-31", "2021-01-31")) |>
  pivot_wider(names_from = date, values_from = zori,values_fn=mean) |>
  mutate(drop = `2021-01-31` - `2020-01-31`) |>
  arrange(drop) |>
  slice_head(n = 10) |>
  select(zip, CountyName, neighborhood, `2020-01-31`, `2021-01-31`, drop)
  covid_drop
```

After cleaning and merging, the resulting tidy dataset contains **`r n_obs`** total observations.  
It includes **`r n_zip`** unique ZIP codes and **`r n_neigh`** unique neighborhoods across the five boroughs of New York City.  

Some ZIP codes exist in the ZIP code dataset but not in the Zillow dataset — for example,  
**`r paste(head(zip_missing, 5), collapse = ", ")`**.  
These ZIP codes are often excluded because they may correspond to **non-residential areas** (e.g., large commercial or industrial zones),  
**P.O. boxes**, or ZIPs with **insufficient rental market data** for Zillow to estimate a rent index.  

Rental prices fluctuated dramatically during the COVID-19 pandemic.  
Comparing January 2021 to January 2020 across all ZIP codes, the table below shows the ten ZIP codes with the largest decline in rent prices:  

### Comments on the TOP 10 rental prices drop ZIP code
```{R Table of TOP 10 rental prices drop ZIP code}
covid_drop
```
The largest decline was in ZIP 10007 (Lower Manhattan), with a drop of about $913, from $6334 to $5422. 
Other steep declines (–$700 to –$750) occurred in 10069 (Upper West Side / Riverside area), 10009 (Lower East Side), and 10016 (Gramercy / Murray Hill).
The smallest of the “top 10” was 10010 (Gramercy / Murray Hill) with a drop of about $684.
All 10 ZIP codes are in Manhattan, indicating that this borough was most heavily affected.
Neighborhoods like Lower Manhattan, Lower East Side, Gramercy, Chelsea, Greenwich Village, and SoHo dominate the list.
These areas are usually dense, expensive rental markets with heavy reliance on office workers, students, and international residents.

During the COVID-19 pandemic (2020–2021), remote work and out-migration reduced demand for Manhattan rentals, leading to dramatic price declines.
Outer-borough neighborhoods (e.g., Queens, Bronx, Staten Island) are absent from the top 10, suggesting less dramatic fluctuations there.

ZIP 10069 has missing neighborhood info, but is known to cover part of the Upper West Side / Riverside South, an upscale area also impacted by decreased demand.